# Generated by Django 5.0.6 on 2024-06-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chest_pain', models.BooleanField()),
                ('spreading_pains', models.BooleanField()),
                ('headaches', models.BooleanField()),
                ('difficulty_breathing', models.BooleanField()),
                ('lost_consciousness', models.BooleanField()),
                ('alcohol_consumption', models.BooleanField()),
                ('smoking', models.BooleanField()),
                ('water_consumption', models.BooleanField()),
                ('physically_active', models.BooleanField()),
                ('blood_pressure', models.CharField(max_length=20)),
            ],
        ),
    ]
